Improve tmux detection

diff --git a/bash/rc b/bash/rc
--- a/bash/rc
+++ b/bash/rc
@@ -81,16 +81,18 @@ done
 
 
 if $INTERACTIVE_SESSION; then
-    # autostart tmux
-    if [ "$TMUX" == "" ]; then
-        tmux attach || tmux || true
+    if type "tmux" &> /dev/null; then
+        # TMUX will have info in it if we're already in a TMUX session
+        if [ "$TMUX" == "" ]; then
+            tmux attach || tmux || true
+        fi
+        #if [ "$PS1" != "" -a "${STARTED_TMUX:-x}" = x -a "${SSH_TTY:-x}" != x ]
+        #then
+        #    export STARTED_TMUX=1
+        #    ~/.local/bin/tmux-shared remote
+        #    echo "tmux failed to start"
+        #fi
     fi
-    #if [ "$PS1" != "" -a "${STARTED_TMUX:-x}" = x -a "${SSH_TTY:-x}" != x ]
-    #then
-    #    export STARTED_TMUX=1
-    #    ~/.local/bin/tmux-shared remote
-    #    echo "tmux failed to start"
-    #fi
 
     # activate virtualenvwrapper
     if [[ -f /usr/local/bin/virtualenvwrapper.sh ]]; then
@@ -126,6 +128,7 @@ if $INTERACTIVE_SESSION; then
     export PATH="$HOME/bin:$PATH"
     export AWS_CREDENTIAL_FILE=~/.aws_credentials
     export GREP_OPTIONS='--exclude-dir=.svn'
+    export SVN_EDITOR=vim
 fi
 
 unset rcfiles
